src/engine/ItemManager.java

/*enemyshipformation의 enemyship에 0,1 값 할당
1이면 hasItem
30퍼센트의 적이 hasItem값 할당
*/

[UPDATE] assignHasItem

---

src/engine/ItemManager.java

update methods addList(), addQueue()

[UPDATE] ItemManager

---

src/engine/ItemManager.java

노은솔
assignitem code 추가
Item.ItemType tmpitem = null;
tmpitem = item_queue.remove();
enemyshipformation.getEnemyShip().get(i).get(j).setItemType(tmpitem);
item_queue.add(tmpitem);

[UPDATE] assignitem

---

src/entity/EnemyShip.java

[UPDATE MATHOD]

---

src/entity/Ship.java
src/screen/GameScreen.java

변수 speed의 타입을 int에서 double로 변경하였습니다.
플레이어 속도가 너무 빨라서 2배에서 1.07배로 변경하였습니다.

[EDIT] entity.Ship, screen.GameScreen

---

.idea/runConfigurations/Run.xml
src/entity/EnemyShip.java
src/entity/Item.java
src/entity/ItemIterator.java
src/entity/Ship.java
src/screen/GameScreen.java

[UPDATE] entity/EnemyShip 
itemDrop()메서드 추가
[UPDATE] entity/ItemIterator 
전역변수 추가 및 drop()메서드 추가
[UPDATE] screen/GameScreen 
전역변수 Item toggle에 대해 volatile 적용(버그)
전역변수 itemiterator 추가
this.item > iterator로 적용하여 한개 이상의 item을 스크린에 표시 가능 케 함

[UPDATE] entity/EnemyShip, entity/ItemIterator , screen/GameScreen 

---

src/engine/Core.java
src/engine/GameState.java
src/entity/Item.java
src/screen/GameScreen.java

[FIX] screen/GameScreen 버그 수정
itempool이 스테이지 넘어갈 때 마다 초기화되는 버그 수정 
[FIX] engine/GameState 생성자 파라미터 수정 final ItemPool > ItemPool

[FIX] screen/GameScreen, engine/GameState

---

.idea/runConfigurations/Run.xml
src/engine/ItemManager.java
src/entity/Ship.java
src/screen/GameScreen.java

[UPDATE] gamescreen

---

src/entity/Ship.java
src/screen/GameScreen.java

GameScreen 클래스 
clearItem() 메서드 구현
총알 속도 증가 구현
Ship 클래스
클래스 변수들을 인스턴스 변수로 변환
초기 비행선 속도, 총알 속도 저장 변수 INIT_xxxx 생성
setInitState() 메서드 구현

[UPDATE]GameScreen.clearItem, Ship.setInitState, cast and add some variables

---

src/engine/ItemManager.java
src/screen/GameScreen.java

[FIX] BugFix

---

src/engine/GameSettings.java
src/engine/ItemManager.java
src/entity/EnemyShipFormation.java
src/entity/Item.java
src/screen/GameScreen.java

[UPDATE] 적 스피드 감소 아이템 구현

---

src/entity/EnemyShip.java
src/screen/GameScreen.java

[FIX] intialize_pointup
gamescreen에 clearpointup 함수를 추가하여 pointupitem만 제외하고 추가함
EnemyShip에 각 적의 포인트 초기화

[FIX] GameScreen, EnemyShip

---

src/entity/Item.java

entity/Item itemsize변경 9*2 x 9*2

[FIX]Itemsize 변경

---

src/engine/Core.java
src/engine/DrawManager.java
src/screen/HelpOperationScreen.java
src/screen/HelpScreen.java
src/screen/Screen.java

SV-7 <인터페이스 통일>

---

src/screen/HelpItemDescriptionScreen.java

SV-14 <[ADD]screen.HelpItemDescription>

---

src/engine/DrawManager.java
src/screen/VolumeScreen.java
src/sound/SoundPlay.java

1. 처음 게임 플레이 시 소리가 너무 크므로 소리 크기 적당하게 재세팅
2. 소리 세팅 방식이 불편하므로 10단계로 나누어 단계 별 세팅

[FIX]Volume screen

---

src/engine/Core.java
src/engine/LoadGameState.java

SV-8 <[ADD] LoadGameState 클래스 추가>

---

src/engine/Core.java
src/engine/DrawManager.java
src/engine/FileManager.java
src/engine/LoadGameState.java
src/screen/SaveInfoScreen.java
src/sound/SoundPlay.java

<[ADD]screen.SaveInfoScreen>
<[EDIT]engine.FileManager, engine.Core, engine.LoadGameState, engine.DrawManager>

SV-43 SaveInfoScreen

---

src/engine/Core.java
src/engine/DrawManager.java
src/engine/FileManager.java
src/engine/PermanentState.java
src/screen/GameScreen.java
src/screen/PauseStateScreen.java
src/screen/SaveInfoScreen.java

SV-8 <[FIX] Core 제어문 개정>

---

log.1
src/engine/Core.java
src/engine/DrawManager.java
src/screen/GameSaveScreen.java
src/screen/PauseStateScreen.java
src/sound/SoundPlay.java

Lsb bugfix

---

src/engine/FileManager.java

FileManager loadCashItem(), saveCashItem(int item, int item_amount) 추가

SV-48 <Cashitem file관련 메서드 2개 추가>

---

src/engine/CashItemManager.java
src/screen/VolumeScreen.java
src/sound/SoundPlay.java

SV-48 <[ADD]CashItemManager 클래스 스켈레톤>
